# Generated by Django 5.1 on 2024-08-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnyVICP2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='icpNumber',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
