# Generated by Django 5.1 on 2024-08-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnyVICP2', '0002_website_icpnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=15)),
                ('content', models.TextField(max_length=15)),
                ('author', models.TextField(max_length=15)),
            ],
        ),
    ]
